name: arody_fotografia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Core
  supabase_flutter: ^2.8.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^14.6.0
  google_fonts: ^6.2.1
  equatable: ^2.0.7
  json_annotation: ^4.9.0

  # UI
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_staggered_grid_view: ^0.7.0
  table_calendar: ^3.2.0
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.13
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
